name: Build Every Commit

on:
    push:
        branches: [ master , test_github_actions]
    pull_request:
        branches: [ master ]

jobs:
    amd64_windows_gcc:
        runs-on: windows-2019
        defaults:
          run:
            shell: msys2 {0}
        steps:
            - uses: actions/checkout@v2
            - uses: msys2/setup-msys2@v2
              with:
                install: gcc make cmake
            - run: mkdir build 
            - run: cmake . -DCMAKE_INSTALL_PREFIX=./dist -DCMAKE_CXX_COMPILER=g++ -Bbuild
            - run: make install
            - run: ls dist/bin
            - uses: actions/upload-artifact@v2
              with:
                name: test
                path: dist/bin/test.exe

    build-windows-x64:
        runs-on: windows-2019
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    submodules: recursive
            -   name: Build
                shell: cmd
                run: |
                    test.exe

