name: Build Every Commit

on:
    push:
        branches: [ master , test_github_actions]
    pull_request:
        branches: [ master ]

jobs:
   

    build-windows-x64:
        runs-on: windows-2019
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    submodules: recursive
            -   name: Build
                shell: cmd
                run: |
                    test.exe

