name: Cross-compile Windows

on:
    push:
        branches: [ master , cc-windows]
    pull_request:
        branches: [ master , cc-windows]

jobs:
    cross_compile_windows:
        runs-on: windows-2019
        strategy:
          matrix:
            compiler: [gcc] #[gcc, clang]
            msystem: [MINGW32 , MINGW64]
            include:
                - msystem: MINGW32
                  mexe: mingw-w64-i686
                - msystem: MINGW64
                  mexe: mingw-w64-x86_64
                - compiler: gcc
                  cc: gcc
                  cxx: g++
                  # does not work with boost for somereason
                #- compiler: clang
                #  cc: clang
                #  cxx: clang++
        defaults:
          run:
            shell: msys2 {0}
        steps:
            - uses: actions/checkout@v2
              with:
                submodules: true
            - uses: msys2/setup-msys2@v2
              with:
                msystem: ${{ matrix.msystem }}
                install:  make cmake
            - name: Install Dependencies
              run: |
                pacman --noconfirm -S ${{ matrix.mexe }}-msmpi
                pacman --noconfirm -S ${{ matrix.mexe }}-winpthreads
                pacman --noconfirm -S ${{ matrix.mexe }}-boost
                pacman --noconfirm -S ${{ matrix.mexe }}-${{ matrix.compiler }}
            - name:  Build
              run: |
                mkdir build
                cd build
                cmake .. -DCMAKE_INSTALL_PREFIX=../dist -DCMAKE_C_COMPILER=${{ matrix.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} -DTOO_C_STATIC=1
                make install
            - name: Test
              run: |
                cd build
                make test
            #- name: OpenCL?
            #  run: ./dist/test/openclTestC.exe
            - uses: actions/upload-artifact@v2
              with:
                name: ${{ matrix.compiler }}-${{ matrix.msystem }}test-bin
                path: dist/

