name: Docker
on:
    push:
        branches: [ docker ]
    pull_request:
        branches: [ docker ]


jobs:
  vm:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install alien libnuma1 wget tar clinfo libxcb-dri3-0 libxcb-dri2-0 rpm
      - uses: actions/cache@v2
        id: cache-packages  # give it a name for checking the cache hit-or-not
        with:
          path: ./l_opencl_p_18.1.0.015/  # what we cache: the folder
          key: ${{ runner.os }}-download
      - run: | 
          wget https://registrationcenter-download.intel.com/akdlm/irc_nas/vcp/15532/l_opencl_p_18.1.0.015.tgz
          tar -xvf  l_opencl_p_18.1.0.015.tgz
        if: steps.cache-packages.outputs.cache-hit != 'true'
      - run: |
          cd l_opencl_p_18.1.0.015/rpm/
          fakeroot alien --to-deb intel-openclrt-18.1.0.015-18.1.0-015.x86_64.rpm
          fakeroot alien --to-deb intel-openclrt-18.1.0.015_18.1.0-16_amd64.deb
          ls
          sudo dpkg -i intel-openclrt-pset-18.1.0.015_18.1.0-16_all.deb
          sudo dpkg -i intel-openclrt-pset-18.1.0.015-18.1.0-015.noarch.rpm.deb
          sudo touch /etc/ld.so.conf.d/intelOpenCL.conf
          sudo echo "/opt/intel/opencl-1.2-6.4.0.25/lib64/clinfo" >> /etc/ld.so.conf.d/intelOpenCL.conf
          sudo mkdir -p /etc/OpenCL/vendors
          sudo ln /opt/intel/opencl-*/etc/intel64.icd /etc/OpenCL/vendors/intel64.icd
          sudo ldconfig
          sudo clinfo

      - run: docker run -t -i --device /dev/dri:/dev/dri -v $(pwd)/wip:/mnt -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY chihchun/opencl-intel:2016R2 clinfo 
      - run: |
          echo This job does not specify a container.
          echo It runs directly on the virtual machine.
        name: Run on VM
  container:
    runs-on: ubuntu-latest
    container: chihchun/opencl-intel
    steps:
      - run: apt-get install clinfo 
      - run: lscpu
      - run: clinfo
      - run: |
          echo This job does specify a container.
          echo It runs in the container instead of the VM.
        name: Run in container
