name: Docker
on:
    push:
        branches: [ docker ]
    pull_request:
        branches: [ docker ]


jobs:
  vm:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install docker
      - run: docker run -t -i --device /dev/dri:/dev/dri -v $(pwd)/wip:/mnt -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY chihchun/opencl-intel:2016R2 clinfo 
      - run: |
          echo This job does not specify a container.
          echo It runs directly on the virtual machine.
        name: Run on VM
  container:
    runs-on: ubuntu-latest
    container: chihchun/opencl-intel
    steps:
      - run: apt-get install clinfo 
      - run: lscpu
      - run: clinfo
      - run: |
          echo This job does specify a container.
          echo It runs in the container instead of the VM.
        name: Run in container
