name: Ubuntu

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    amd64_windows_gcc:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
                run: sudo apt-get install -y gcc make cmake
            - run: mkdir build 
            - run: cmake . -DCMAKE_INSTALL_PREFIX=./dist -DCMAKE_CXX_COMPILER=g++ -Bbuild
            - run: make -C build install
            - run: ls dist/bin
            - uses: actions/upload-artifact@v2
              with:
                name: test
                path: dist/bin/test.exe

