name: Ubuntu

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    amd64_windows_gcc:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            compiler: [gcc, clang]
        steps:
            - uses: actions/checkout@v2
            - run: sudo apt-get install -y make cmake
            - run: sudo apt-get install -y gcc
              if: ${{ matrix.compiler == 'gcc' }}
            - run: sudo apt-get install -y clang
              if: ${{ matrix.compiler == 'clang' }}
            - run: mkdir build 
            - run: cmake . -DCMAKE_INSTALL_PREFIX=./dist -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -DCMAKE_C_COMPILER=${{ matrix.compiler }} -Bbuild
            - run: make -C build install
            - run: ls -la dist/bin/
            - uses: actions/upload-artifact@v2
              with:
                name: test-bin
                path: dist/bin/

