name: Ubuntu

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
env:        
    cc: [gcc,clang]
    cxx: [g++,clang++]

jobs:
    compile_ubuntu:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            compiler: [0, 1]
        steps:
            - uses: actions/checkout@v2
            - run: sudo apt-get install -y make cmake
            - run: sudo apt-get install -y gcc
              if: ${{ matrix.compiler == '0' }}
            - run: sudo apt-get install -y clang
              if: ${{ matrix.compiler == '1' }}
            - run: mkdir build 
            - run: cmake . -DCMAKE_INSTALL_PREFIX=./dist  -DCMAKE_C_COMPILER=${{ env.cc[matrix.compiler] }} -DCMAKE_CXX_COMPILER=${{ env.cxx[matrix.compiler] }} -Bbuild
            - run: make -C build install
            - run: ls -la dist/bin/
            - uses: actions/upload-artifact@v2
              with:
                name: test-bin
                path: dist/bin/

