name: Mac

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    macos_gcc:
        runs-on: macos-10.15
        steps:
            - uses: actions/checkout@v2
            - run: mkdir build 
            - run: cmake . -DCMAKE_INSTALL_PREFIX=./dist -DCMAKE_CXX_COMPILER=g++ -Bbuild
            - run: make -C build install
            - run: ls -la dist/bin/
            - uses: actions/upload-artifact@v2
              with:
                name: test
                path: dist/bin/clewTTestC

