name: Mac

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    compile_macos:
        runs-on: macos-10.15
        steps:
            - uses: actions/checkout@v2
              with:
                submodules: true
            - run: brew install boost
            - run: mkdir build 
            - run: |
                cd build
                cmake .. -DCMAKE_INSTALL_PREFIX=../dist -DCMAKE_CXX_COMPILER=g++
                make install
            - run: ls -la dist/bin/
            - uses: actions/upload-artifact@v2
              with:
                name: test-bin
                path: dist/bin/

