name: Mac

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    compile_macos:
        runs-on: macos-10.15
        steps:
            - uses: actions/checkout@v2
              with:
                submodules: true
            - name: Install Dependencies
              run: brew install boost openmpi libomp 
            - run: brew --prefix libomp
            - name:  Build
              run: |
                mkdir build
                cd build
                cmake .. -DCMAKE_INSTALL_PREFIX=../dist -DTOO_TEST_MPI=1
                make install
            - name: Test
              run: |
                cd build
                make test
            #- name: OpenCL?
            #  run: ./dist/test/openclTestC
            - uses: actions/upload-artifact@v2
              with:
                name: test-bin
                path: dist/

