name: Windows

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    compile_windows:
        runs-on: windows-2019
        steps:
            - uses: actions/checkout@v2
              with:
                submodules: true
            #- name: env
            #  run: echo "::set-env name=BOOST_ROOT::$env:BOOST_ROOT_1_69_0"
            #- name: env2
            #  run: echo "::set-env name=BOOST_INCLUDE_DIR::$env:BOOST_ROOT_1_72_0\include"
            #- name: env3
            #  run: echo "::set-env name=BOOST_LIBRARY_DIR::$env:BOOST_ROOT_1_69_0\lib"

            - run: dir ${{ env.BOOST_ROOT_1_72_0}}\include
            - run: dir ${{ env.BOOST_ROOT_1_72_0}}\include\boost
            - uses: ashutoshvarma/action-cmake-build@master
              with:
                build-dir: ${{ runner.workspace }}\build
                # will set the CC & CXX for cmake
                cc: cl
                cxx: cl
                build-type: Release
                # Extra options pass to cmake while configuring project
                configure-options: -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}\dist -DBOOST_ROOT:PATH=${{BOOST_ROOT_1_72_0}} -DBOOST_INCLUDE_DIR:PATH=${{BOOST_ROOT_1_72_0}}

                install-build: true
            #- run: cl.exe --version
            #- run: md build 
            #- run: |
            #    cd build
            #    cmake .. -DCMAKE_INSTALL_PREFIX=../dist -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl
            #    make install
            #- run: dir dist/bin/
            - uses: actions/upload-artifact@v2
              with:
                name: win-test-bin
                path: dist/bin/