name: Windows

on:
    push:
        branches: [ master , windows ]
    pull_request:
        branches: [ master , windows ]

jobs:
    compile_windows:
        runs-on: windows-2019
        steps:
            - uses: actions/checkout@v2
              with:
                submodules: true
            - name: Set Boost Environment Variables 
              run: |
                echo "::set-env name=BOOST_ROOT::$env:BOOST_ROOT_1_69_0"
                echo "::set-env name=BOOST_INCLUDE_DIR::$env:BOOST_ROOT_1_69_0\include"
                echo "::set-env name=BOOST_LIBRARY_DIR::$env:BOOST_ROOT_1_69_0\lib"
            - name: Install MSMPI
              run: |
                curl.exe -o msmpisdk.msi https://download.microsoft.com/download/A/E/0/AE002626-9D9D-448D-8197-1EA510E297CE/msmpisdk.msi
                msiexec.exe /i msmpisdk.msi /passive
            - uses: ashutoshvarma/action-cmake-build@master
              with:
                build-dir: ${{ runner.workspace }}\build
                # will set the CC & CXX for cmake
                cc: cl
                cxx: cl
                build-type: Release
                # Extra options pass to cmake while configuring project
                configure-options: -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}\dist -DTOO_BOOST_STATIC=1
                run-test: true
                install-build: true
            - uses: actions/upload-artifact@v2
              with:
                name: win-test-bin
                path: ${{runner.workspace}}\dist\
