name: Windows

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    amd64_windows_gcc:
        runs-on: windows-2019
        defaults:
          run:
            shell: msys2 {0}
        steps:
            - uses: actions/checkout@v2
            - uses: msys2/setup-msys2@v2
              with:
                install: gcc make cmake
            - run: mkdir build 
            - run: cmake . -DCMAKE_INSTALL_PREFIX=./dist -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -Bbuild
            - run: make -C build install
            - run: ls -la dist/bin/
            - uses: actions/upload-artifact@v2
              with:
                name: test-bin
                path: dist/bin/

