name: Windows

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    amd64_windows_gcc:
        runs-on: windows-2019
        strategy:
          matrix:
            compiler: [gcc, clang]
            msystem: [MINGW32, MINGW64]
        defaults:
          run:
            shell: msys2 {0}
        steps:
            - uses: actions/checkout@v2
            - uses: msys2/setup-msys2@v2
              with:
                install:  make cmake
            - name: Setup Compiler
              - run: pacman --noconfirm -S gcc
                if: ${{ matrix.compiler == 'gcc' }}
              - run: pacman --noconfirm -S mingw-w64-x86_64-clang
                if: ${{ (matrix.msystem == 'MINGW64') && (matrix.compiler == 'clang') }}
              - run: pacman --noconfirm -S mingw-w64-i686-clang
                if: ${{ (matrix.msystem == 'MINGW32') && (matrix.compiler == 'clang') }}
              - run: ${{ matrix.compiler }} --version
            - run: ls -la /usr/bin
            - run: mkdir build 
            - run: cmake . -DCMAKE_INSTALL_PREFIX=./dist -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -DCMAKE_C_COMPILER=${{ matrix.compiler }} -Bbuild
            - run: make -C build install
            - run: ls -la dist/bin/
            - uses: actions/upload-artifact@v2
              with:
                name: test-bin
                path: dist/bin/

